#

PLUGIN=		forum

FILES=		config.php debug.php functions.inc history.txt \
		readme.html readme.jp upgrade.inc v2.6_changes.txt \
		v2.7_changes.txt v2.7.1_changes.txt v2.7.2_changes.txt
DIRS=		language sql system templates themefiles

include ../../GNUmakefile.plugins
include ../../GNUmakefile.common
