#

PLUGIN=		tkgmaps

FILES=		INSTALL README_ja.html config.php \
		function_tkgmaps-admin.php function_tkgmaps.php functions.inc \
		install.html install_ja.html

include ../../GNUmakefile.plugins
include ../../GNUmakefile.common
