#

# Basic plugins for Geeklog Japanese release.
SUBDIR=	calendarjp japanize

# Additional plugins for Geeklog Japanese extended release.
ESUBDIR=	autotags captcha custommenu dataproxy dbman filemgmt forum
ESUBDIR+=	mycaljp nmoxtopicown sitemap themedit

include ../GNUmakefile.common
