#

SUBDIR=	calendarjp japanize

ifeq ($(EXTENDED), true)
SUBDIR+=	autotags captcha custommenu dataproxy dbman filemgmt forum
SUBDIR+=	 mycaljp nmoxqrblock nmoxtopicown sitemap themedit tkgmaps
endif

include ../GNUmakefile.common
