#

PLUGIN=		nmoxqrblock

FILES=		autoinstall.php config.php configuration_validation.php functions.inc install_defaults.php readme_ja.txt
DIRS=		language templates

include ../../GNUmakefile.plugins
include ../../GNUmakefile.common
