#

PLUGIN=		filemgmt

FILES=		config.php filemgmt.php functions.inc history readme.htm \
		update_20090602.html
MAKEPUBDIRS=	filemgmt_data/category_snaps filemgmt_data/files/tmp \
		filemgmt_data/snaps/tmp
PUBDIRMODE=	0775

include ../../GNUmakefile.plugins
include ../../GNUmakefile.common
