#

FILES=		custom_cellular.php custom_mail_jp.php
ifeq ($(EXTENDED), true)
FILES+=		custom_getstaticpage.php phpblock_lastarticles.php
FILES+=		phpblock_showrights.php phpblock_sitemapmenu.php
FILES+=		phpblock_stats.php phpblock_themetester.php
endif

GLDESTDIR=	$(GLDIR)/system/custom

install: install-myfiles

include ../GNUmakefile.common
