#

# Basic custom functions for Geeklog Japanese release.
FILES=		custom_cellular.php

# Additional custom functions for Geeklog Japanese extended release.
EFILES+=	custom_forcethemechange.php custom_getstaticpage.php
EFILES+=	custom_templatesetvars.php
EFILES+=	phpblock_lastarticles.php phpblock_lastarticles.thtml
EFILES+=	phpblock_showrights.php phpblock_sitemapmenu.php
EFILES+=	phpblock_stats.php phpblock_themetester.php
EFILES+=	useragent.class.php

GLDESTDIR=	$(GLDIR)/system/custom

install: install-myfiles

include ../GNUmakefile.common
