#

PLUGIN=		forum

FILES=		autoinstall.php config.php functions.inc history.txt \
		install_defaults.php readme.html readme_ja.txt upgrade.inc \
		v2.7_changes.txt v2.7.1_changes.txt v2.7.2_changes.txt \
		v2.7.3_changes.txt v2.7.4_changes.txt
DIRS=		include language sql themefiles

include ../../GNUmakefile.plugins
include ../../GNUmakefile.common
