# $Id$

PLUGIN=		japanize

FILES=		autoinstall.php functions.inc install_defaults.php readme_ja.txt upgrade.inc version.php
DIRS=		custom doc language lib sql templates

include ../../GNUmakefile.plugins
include ../../GNUmakefile.common
