#

PLUGIN=		custommenu

FILES=		README_JP config.php functions.inc install_defaults.php \
		readme_jp.html readme_jp_1.5.html
DIRS=		bonus language layout sql templates

include ../../GNUmakefile.plugins
include ../../GNUmakefile.common
